import argparse
from pathlib import Path

import numpy as np
import pandas as pd


LOCATION_LABELS = [
    "Left Infraclinoid Internal Carotid Artery",
    "Right Infraclinoid Internal Carotid Artery",
    "Left Supraclinoid Internal Carotid Artery",
    "Right Supraclinoid Internal Carotid Artery",
    "Left Middle Cerebral Artery",
    "Right Middle Cerebral Artery",
    "Anterior Communicating Artery",
    "Left Anterior Cerebral Artery",
    "Right Anterior Cerebral Artery",
    "Left Posterior Communicating Artery",
    "Right Posterior Communicating Artery",
    "Basilar Tip",
    "Other Posterior Circulation",
]

# Normalized (x, y) anchors in a 2D head view prior map.
# These are weak anatomical priors, not true lesion coordinates.
LOCATION_ANCHORS = {
    "Left Infraclinoid Internal Carotid Artery": (0.40, 0.62),
    "Right Infraclinoid Internal Carotid Artery": (0.60, 0.62),
    "Left Supraclinoid Internal Carotid Artery": (0.42, 0.53),
    "Right Supraclinoid Internal Carotid Artery": (0.58, 0.53),
    "Left Middle Cerebral Artery": (0.30, 0.46),
    "Right Middle Cerebral Artery": (0.70, 0.46),
    "Anterior Communicating Artery": (0.50, 0.40),
    "Left Anterior Cerebral Artery": (0.43, 0.36),
    "Right Anterior Cerebral Artery": (0.57, 0.36),
    "Left Posterior Communicating Artery": (0.43, 0.57),
    "Right Posterior Communicating Artery": (0.57, 0.57),
    "Basilar Tip": (0.50, 0.55),
    "Other Posterior Circulation": (0.50, 0.70),
}


def make_gaussian(h: int, w: int, cx: float, cy: float, sigma: float) -> np.ndarray:
    y, x = np.mgrid[0:h, 0:w]
    return np.exp(-(((x - cx) ** 2 + (y - cy) ** 2) / (2.0 * sigma**2))).astype(np.float32)


def resolve_prob_column(df: pd.DataFrame, label: str) -> str:
    c1 = f"{label}_Prob"
    c2 = label
    if c1 in df.columns:
        return c1
    if c2 in df.columns:
        return c2
    raise KeyError(f"Missing probability column for '{label}' (expected '{c1}' or '{c2}')")


def save_image_uint8(img: np.ndarray, out_path: Path):
    try:
        import cv2

        cv2.imwrite(str(out_path), img)
        return "opencv"
    except Exception:
        from PIL import Image

        Image.fromarray(img).save(out_path)
        return "pillow"


def colorize_heatmap(heat_uint8: np.ndarray) -> np.ndarray:
    try:
        import cv2

        return cv2.applyColorMap(heat_uint8, cv2.COLORMAP_JET)
    except Exception:
        # Fallback: simple red channel visualization
        rgb = np.zeros((heat_uint8.shape[0], heat_uint8.shape[1], 3), dtype=np.uint8)
        rgb[..., 0] = heat_uint8
        return rgb


def build_prior_heatmap(
    row: pd.Series,
    gaussian_maps: dict,
    prob_columns: dict,
    det_prob_col: str | None,
    use_detection_weight: bool,
) -> tuple[np.ndarray, dict]:
    det_weight = float(row[det_prob_col]) if (use_detection_weight and det_prob_col and det_prob_col in row) else 1.0
    det_weight = max(0.0, min(1.0, det_weight))

    per_location_weight = {}
    heat = None
    for label in LOCATION_LABELS:
        p = float(row[prob_columns[label]])
        p = max(0.0, min(1.0, p))
        w = p * det_weight
        per_location_weight[label] = w
        g = gaussian_maps[label]
        heat = (w * g) if heat is None else (heat + w * g)

    if heat is None:
        heat = np.zeros_like(next(iter(gaussian_maps.values())), dtype=np.float32)

    return heat, per_location_weight


def main():
    parser = argparse.ArgumentParser(description="Weak localization from binary + 13 area probabilities.")
    parser.add_argument(
        "--pred_csv",
        type=Path,
        default=Path("outputs/fusion_20260309_164325_final_experiment/predictions.csv"),
        help="Path to predictions.csv generated by inference_fusion.py",
    )
    parser.add_argument(
        "--out_dir",
        type=Path,
        default=Path("outputs/fusion_20260309_164325_final_experiment/location_prior_visuals"),
        help="Output directory for heatmaps and masks",
    )
    parser.add_argument("--width", type=int, default=256)
    parser.add_argument("--height", type=int, default=256)
    parser.add_argument(
        "--sigma",
        type=float,
        default=18.0,
        help="Gaussian spread in pixels for each anatomical area prior",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.45,
        help="Threshold on normalized heatmap to create binary highlight mask",
    )
    parser.add_argument(
        "--top_k",
        type=int,
        default=3,
        help="Top-k probable anatomical areas to report",
    )
    parser.add_argument(
        "--no_detection_weight",
        action="store_true",
        help="Do not multiply location probs by aneurysm probability",
    )

    args = parser.parse_args()

    df = pd.read_csv(args.pred_csv)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    prob_columns = {label: resolve_prob_column(df, label) for label in LOCATION_LABELS}
    det_prob_col = "Aneurysm_Probability" if "Aneurysm_Probability" in df.columns else None

    gaussian_maps = {}
    for label in LOCATION_LABELS:
        nx, ny = LOCATION_ANCHORS[label]
        cx = nx * (args.width - 1)
        cy = ny * (args.height - 1)
        gaussian_maps[label] = make_gaussian(args.height, args.width, cx, cy, args.sigma)

    summary_rows = []
    writer_name = None

    for idx, row in df.iterrows():
        heat, loc_weights = build_prior_heatmap(
            row=row,
            gaussian_maps=gaussian_maps,
            prob_columns=prob_columns,
            det_prob_col=det_prob_col,
            use_detection_weight=not args.no_detection_weight,
        )

        maxv = float(heat.max())
        if maxv > 0:
            heat_norm = heat / maxv
        else:
            heat_norm = np.zeros_like(heat, dtype=np.float32)

        heat_uint8 = (np.clip(heat_norm, 0.0, 1.0) * 255.0).astype(np.uint8)
        binary = (heat_norm >= args.threshold).astype(np.uint8) * 255

        color = colorize_heatmap(heat_uint8)

        uid = str(row["SeriesInstanceUID"]) if "SeriesInstanceUID" in row else f"sample_{idx:04d}"
        uid = uid.replace("/", "_").replace("\\", "_")

        heat_path = args.out_dir / f"{idx:04d}_{uid}_heatmap.png"
        mask_path = args.out_dir / f"{idx:04d}_{uid}_mask.png"
        writer_name = save_image_uint8(color, heat_path)
        writer_name = save_image_uint8(binary, mask_path)

        sorted_locs = sorted(loc_weights.items(), key=lambda x: x[1], reverse=True)
        top_locs = sorted_locs[: max(1, args.top_k)]

        summary_rows.append(
            {
                "sample_index": idx,
                "SeriesInstanceUID": row.get("SeriesInstanceUID", ""),
                "Aneurysm_Probability": row.get("Aneurysm_Probability", np.nan),
                "heat_max_raw": maxv,
                "highlight_pixels": int((binary > 0).sum()),
                "top1_location": top_locs[0][0],
                "top1_weight": float(top_locs[0][1]),
                "top2_location": top_locs[1][0] if len(top_locs) > 1 else "",
                "top2_weight": float(top_locs[1][1]) if len(top_locs) > 1 else np.nan,
                "top3_location": top_locs[2][0] if len(top_locs) > 2 else "",
                "top3_weight": float(top_locs[2][1]) if len(top_locs) > 2 else np.nan,
                "heatmap_path": str(heat_path),
                "mask_path": str(mask_path),
            }
        )

    summary_df = pd.DataFrame(summary_rows)
    summary_path = args.out_dir / "location_prior_summary.csv"
    summary_df.to_csv(summary_path, index=False)

    print(f"Saved visuals in: {args.out_dir}")
    print(f"Image writer: {writer_name}")
    print(f"Summary CSV: {summary_path}")
    print(f"Total samples: {len(summary_df)}")
    print(f"Samples with any highlighted pixels: {(summary_df['highlight_pixels'] > 0).sum()}")


if __name__ == "__main__":
    main()
